services:
  # PHP + Apache
  web:
    build: .
    container_name: lamp-php-container
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - lamp-network

  # MySQL Database
  db:
    image: mysql:8.0.23
    container_name: lamp-mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bank_on_food
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lamp-network

  # Database Management UI
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: lamp-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - lamp-network

networks:
  lamp-network:
    driver: bridge

volumes:
  db_data: